# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1452aa1c712a1b144e111898e01a95a6f9f04a8a3515e737b76dabd5f97c31488417974ea4d08cb29db259812e56c3ee9395d9e1aac1aa99de6d27ddc10ea482

test:
  secret_key_base: 97bbbe3272b7c831ba860e108d3996cc2a80a3e027d19ff424563c9bb2374916349f56155e01175eca6ed7815d6eba22e60d672c33e56088abf89c346562d8fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
